/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSICION;

import DATABASE.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author rlope
 */
public class O_Residentes_Med extends javax.swing.JPanel {

    /**
     * Creates new form O_Residentes_Med
     */
    public O_Residentes_Med() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResidentesMed = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtMedicamento = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        tblResidentesMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre del Residente", "Medicamento Asignado", "Cantidad Asignado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResidentesMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResidentesMedMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblResidentesMed);
        if (tblResidentesMed.getColumnModel().getColumnCount() > 0) {
            tblResidentesMed.getColumnModel().getColumn(0).setHeaderValue("Código");
            tblResidentesMed.getColumnModel().getColumn(1).setHeaderValue("Nombre del Residente");
            tblResidentesMed.getColumnModel().getColumn(2).setHeaderValue("Medicamento Asignado");
            tblResidentesMed.getColumnModel().getColumn(3).setHeaderValue("Cantidad Asignado");
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Medicamento: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad: ");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(51, 255, 51));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Asignar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(0, 102, 255));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Editar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(102, 255, 255));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Linpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nombre: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(79, 79, 79))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedicamento)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(383, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        String nombre = txtNombre.getText();
    String medicamento = txtMedicamento.getText();
    String cantidad = txtCantidad.getText();
    
    // Verificar que los campos estén llenos
    if (nombre.isEmpty() || medicamento.isEmpty() || cantidad.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos");
        return;
    }
    // Verificar si el residente existe
    if (!existeResidente(nombre)) {
        JOptionPane.showMessageDialog(null, "El residente especificado no existe");
        return;
    }

    // Verificar si el medicamento existe
    if (!existeMedicamento(medicamento)) {
        JOptionPane.showMessageDialog(null, "El medicamento especificado no existe");
        return;
    }
    // Verificar si el registro ya existe antes de insertarlo
    if (existeRegistro(nombre, medicamento)) {
        JOptionPane.showMessageDialog(null, "El registro para este residente y medicamento ya existe.");
        return;
    }

    try {
        Connection con = Conexion.getConexion();
        PreparedStatement ps = con.prepareStatement("INSERT INTO residentes_medicamentos(residente_id, medicamento_id, cantidad) VALUES (?, ?, ?)");

        // Obtener los IDs correspondientes a partir de los nombres
        int residenteId = obtenerIdResidente(nombre);
        int medicamentoId = obtenerIdMedicamento(medicamento);

        // Asignar los valores a los parámetros
        ps.setInt(1, residenteId);
        ps.setInt(2, medicamentoId);
        ps.setString(3, cantidad);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Registro Guardado");

        // Limpiar los campos o realizar otras acciones necesarias
        limpiar();
        cargarTabla();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.toString());
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Verificar si el residente existe en la base de datos
private boolean existeResidente(String nombre) {
    boolean existe = false;

    try {
        Connection con = Conexion.getConexion();
        PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM residentes WHERE nombre = ?");
        ps.setString(1, nombre);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int count = rs.getInt(1);
            existe = count > 0;
        }

        rs.close();
        ps.close();
        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return existe;
}

// Verificar si el medicamento existe en la base de datos
private boolean existeMedicamento(String medicamento) {
    boolean existe = false;

    try {
        Connection con = Conexion.getConexion();
        PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM medicamentos WHERE nombre = ?");
        ps.setString(1, medicamento);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int count = rs.getInt(1);
            existe = count > 0;
        }

        rs.close();
        ps.close();
        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return existe;
}

// Verificar si ya existe un registro para el residente y el medicamento seleccionados
private boolean existeRegistro(String nombreResidente, String nombreMedicamento) {
    boolean existe = false;

    try {
        Connection con = Conexion.getConexion();
        PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM residentes_medicamentos rm " +
                                                     "JOIN residentes r ON rm.residente_id = r.id " +
                                                     "JOIN medicamentos m ON rm.medicamento_id = m.id " +
                                                     "WHERE r.nombre = ? AND m.nombre = ?");
        ps.setString(1, nombreResidente);
        ps.setString(2, nombreMedicamento);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int count = rs.getInt(1);
            existe = count > 0;
        }

        rs.close();
        ps.close();
        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return existe;
}
    
    private int obtenerIdResidente(String nombre) throws SQLException {
    int idResidente = -1; // Valor predeterminado si no se encuentra el ID
    Connection con = Conexion.getConexion();
    PreparedStatement ps = con.prepareStatement("SELECT id FROM residentes WHERE nombre = ?");
    ps.setString(1, nombre);
    ResultSet rs = ps.executeQuery();
    if (rs.next()) {
        idResidente = rs.getInt("id");
    }
    return idResidente;
}

private int obtenerIdMedicamento(String medicamento) throws SQLException {
    int idMedicamento = -1; // Valor predeterminado si no se encuentra el ID
    Connection con = Conexion.getConexion();
    PreparedStatement ps = con.prepareStatement("SELECT id FROM medicamentos WHERE nombre = ?");
    ps.setString(1, medicamento);
    ResultSet rs = ps.executeQuery();
    if (rs.next()) {
        idMedicamento = rs.getInt("id");
    }
    return idMedicamento;
}
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

       
       int fila = tblResidentesMed.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Seleccione una fila de la tabla");
        return;
    }
    
    int id = Integer.parseInt(tblResidentesMed.getValueAt(fila, 0).toString());
    String nombre = txtNombre.getText();
    String medicamento = txtMedicamento.getText();
    String cantidad = txtCantidad.getText();

    modificarRegistro(id, nombre, medicamento, cantidad);
    }//GEN-LAST:event_btnModificarActionPerformed
private void modificarRegistro(int id, String nombre, String medicamento, String cantidad) {
    try {
        Connection con = Conexion.getConexion();
        PreparedStatement ps = con.prepareStatement("UPDATE residentes_medicamentos SET residente_id=?, medicamento_id=?, cantidad=? WHERE id=?");

        // Obtener los IDs correspondientes a partir de los nombres
        int residenteId = obtenerIdResidente(nombre);
        int medicamentoId = obtenerIdMedicamento(medicamento);

        // Asignar los valores a los parámetros
        ps.setInt(1, residenteId);
        ps.setInt(2, medicamentoId);
        ps.setString(3, cantidad);
        ps.setInt(4, id);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Registro Modificado");

        // Limpiar los campos o realizar otras acciones necesarias
        limpiar();
        cargarTabla();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.toString());
    }
}

    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

int fila = tblResidentesMed.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Seleccione una fila de la tabla");
        return;
    }
    
    int id = Integer.parseInt(tblResidentesMed.getValueAt(fila, 0).toString());

    eliminarRegistro(id);
    }//GEN-LAST:event_btnEliminarActionPerformed
private void eliminarRegistro(int id) {
    try {
        Connection con = Conexion.getConexion();
        PreparedStatement ps = con.prepareStatement("DELETE FROM residentes_medicamentos WHERE id=?");
        ps.setInt(1, id);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Registro Eliminado");

        // Limpiar los campos o realizar otras acciones necesarias
        // limpiar();
        cargarTabla();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.toString());
    }
}

    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblResidentesMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResidentesMedMouseClicked
        // TODO add your handling code here:
     try {
        int fila = tblResidentesMed.getSelectedRow();
        int id = Integer.parseInt(tblResidentesMed.getValueAt(fila, 0).toString());
        PreparedStatement ps;
        ResultSet rs;

        Connection con = Conexion.getConexion();

        ps = con.prepareStatement("SELECT residente_id, medicamento_id, cantidad FROM residentes_medicamentos WHERE id = ?");
        ps.setInt(1, id);
        rs = ps.executeQuery();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        while (rs.next()) {
            int residenteId = rs.getInt("residente_id");
            String nombreResidente = obtenerNombreResidente(residenteId); // Obtener el nombre del residente
            txtNombre.setText(nombreResidente);

            int medicamentoId = rs.getInt("medicamento_id");
            String nombreMedicamento = obtenerNombreMedicamento(medicamentoId); // Obtener el nombre del medicamento
            txtMedicamento.setText(nombreMedicamento);

            int cantidad = rs.getInt("cantidad");
            txtCantidad.setText(String.valueOf(cantidad));

            
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.toString());
    }

    }//GEN-LAST:event_tblResidentesMedMouseClicked

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseMoved
private void cargarTabla() {
    DefaultTableModel modeloTabla = (DefaultTableModel) tblResidentesMed.getModel();
    modeloTabla.setRowCount(0);

    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd;
    int columnas;

    int[] anchos = {30, 50, 50, 150};

    for (int i = 0; i < tblResidentesMed.getColumnCount(); i++){
        tblResidentesMed.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
    }

    try {
        Connection con = Conexion.getConexion();
        ps = con.prepareStatement("SELECT id, residente_id, medicamento_id, cantidad FROM residentes_medicamentos");
        rs = ps.executeQuery();
        rsmd = rs.getMetaData();
        columnas = rsmd.getColumnCount();

        while (rs.next()) {
            Object[] fila = new Object[columnas];
            for (int indice = 0; indice < columnas; indice++) {
                if (indice == 1) { // Columna del residente_id
                    int residenteId = rs.getInt(indice + 1);
                    String nombreResidente = obtenerNombreResidente(residenteId); // Obtener el nombre del residente
                    fila[indice] = nombreResidente;
                } else if (indice == 2) { // Columna del medicamento_id
                    int medicamentoId = rs.getInt(indice + 1);
                    String nombreMedicamento = obtenerNombreMedicamento(medicamentoId); // Obtener el nombre del medicamento
                    fila[indice] = nombreMedicamento;
                } else {
                    fila[indice] = rs.getObject(indice + 1);
                }
            }
            modeloTabla.addRow(fila);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.toString());
    }
}

private String obtenerNombreResidente(int residenteId) throws SQLException {
    String nombreResidente = "";
    Connection con = Conexion.getConexion();
    PreparedStatement ps = con.prepareStatement("SELECT nombre FROM residentes WHERE id = ?");
    ps.setInt(1, residenteId);
    ResultSet rs = ps.executeQuery();
    if (rs.next()) {
        nombreResidente = rs.getString("nombre");
    }
    return nombreResidente;
}

private String obtenerNombreMedicamento(int medicamentoId) throws SQLException {
    String nombreMedicamento = "";
    Connection con = Conexion.getConexion();
    PreparedStatement ps = con.prepareStatement("SELECT nombre FROM medicamentos WHERE id = ?");
    ps.setInt(1, medicamentoId);
    ResultSet rs = ps.executeQuery();
    if (rs.next()) {
        nombreMedicamento = rs.getString("nombre");
    }
    return nombreMedicamento;
}
private void limpiar(){
        txtNombre.setText("");
        txtMedicamento.setText("");
        txtCantidad.setText("");
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblResidentesMed;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
